# Generated by Django 3.0.2 on 2020-01-13 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CMCElectricModel',
            new_name='Electric',
        ),
    ]
