# Generated by Django 3.0.2 on 2020-01-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_auto_20200113_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energy',
            name='electric_use',
        ),
        migrations.AddField(
            model_name='energy',
            name='electric',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='energy',
            name='heat',
            field=models.FloatField(null=True),
        ),
    ]
