# Generated by Django 3.0.2 on 2020-01-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0005_auto_20200124_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
