# Generated by Django 3.0.2 on 2020-01-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0006_auto_20200124_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
